FROM python:3.13.10-slim

# copy uv binary
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/

WORKDIR /app

# aktifkan virtual environment
ENV PATH="/app/.venv/bin:$PATH"

# copy dependency metadata (cache-friendly)
COPY pyproject.toml uv.lock .python-version ./

# install dependency secara reproducible
RUN uv sync --locked

# copy source code
COPY pipeline.py pipeline.py

ENTRYPOINT ["python", "pipeline.py"]